name: torch
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9

  # Core ML & Data Processing
  - pytorch>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - h5py>=3.7.0

  # Gravitational Wave Analysis
  - lal>=7.1.0
  - bilby>=1.0.0
  - gwsurrogate>=1.0.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # Optimization
  - pip:
    - pytorch_optimizer>=0.1.0

  # Utilities
  - joblib>=1.3.0
  - pyspherical>=0.1.0

  # Data Processing
  - scikit-learn>=1.2.0
  - pandas>=2.0.0

  # Development tools
  - jupyter
  - ipykernel
  - black
  - isort
  - flake8

  # Testing
  - pytest
  - pytest-cov
